//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.QuanLyKyThi.DuLieu
{

    public partial class GiaoVien : BaseObject
    {
        string fMa;
        public string Ma
        {
            get { return fMa; }
            set { SetPropertyValue<string>("Ma", ref fMa, value); }
        }
        string fHoDem;
        public string HoDem
        {
            get { return fHoDem; }
            set { SetPropertyValue<string>("HoDem", ref fHoDem, value); }
        }
        string fTen;
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>("Ten", ref fTen, value); }
        }
        string fNgaySinh;
        public string NgaySinh
        {
            get { return fNgaySinh; }
            set { SetPropertyValue<string>("NgaySinh", ref fNgaySinh, value); }
        }
        string fGioiTinh;
        public string GioiTinh
        {
            get { return fGioiTinh; }
            set { SetPropertyValue<string>("GioiTinh", ref fGioiTinh, value); }
        }
        string fDonVi;
        public string DonVi
        {
            get { return fDonVi; }
            set { SetPropertyValue<string>("DonVi", ref fDonVi, value); }
        }
        string fDienThoai;
        public string DienThoai
        {
            get { return fDienThoai; }
            set { SetPropertyValue<string>("DienThoai", ref fDienThoai, value); }
        }
        string fEmailLienHe;
        public string EmailLienHe
        {
            get { return fEmailLienHe; }
            set { SetPropertyValue<string>("EmailLienHe", ref fEmailLienHe, value); }
        }
        string fHinhAnh;
        public string HinhAnh
        {
            get { return fHinhAnh; }
            set { SetPropertyValue<string>("HinhAnh", ref fHinhAnh, value); }
        }
    }

}
