//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.QuanLyKyThi.DuLieu
{

    public partial class KhoaThi : BaseObject
    {
        string fMa;
        [DevExpress.Xpo.DisplayName(@"Mã khóa thi")]
        public string Ma
        {
            get { return fMa; }
            set { SetPropertyValue<string>("Ma", ref fMa, value); }
        }
        string fTen;
        [DevExpress.Xpo.DisplayName(@"Khóa thi")]
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>("Ten", ref fTen, value); }
        }
        DateTime fKhoaNgay;
        [DevExpress.Xpo.DisplayName(@"Khóa ngày")]
        public DateTime KhoaNgay
        {
            get { return fKhoaNgay; }
            set { SetPropertyValue<DateTime>("KhoaNgay", ref fKhoaNgay, value); }
        }
        string fGhiChu;
        [DevExpress.Xpo.DisplayName(@"Ghi chú")]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>("GhiChu", ref fGhiChu, value); }
        }
        [Association(@"MonThiReferencesKhoaThi"), Aggregated]
        public XPCollection<MonThi> MonThis { get { return GetCollection<MonThi>("MonThis"); } }
        [Association(@"GiamThiReferencesKhoaThi"), Aggregated]
        public XPCollection<GiamThi> GiamThis { get { return GetCollection<GiamThi>("GiamThis"); } }
        [Association(@"ThiSinhReferencesKhoaThi"), Aggregated]
        public XPCollection<ThiSinh> ThiSinhs { get { return GetCollection<ThiSinh>("ThiSinhs"); } }
    }

}
