//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.QuanLyKyThi.DuLieu
{

    public partial class KhoiLop : BaseObject
    {
        string fMa;
        [DevExpress.Xpo.DisplayName(@"Mã khối lớp")]
        public string Ma
        {
            get { return fMa; }
            set { SetPropertyValue<string>("Ma", ref fMa, value); }
        }
        string fTen;
        [DevExpress.Xpo.DisplayName(@"Khối lớp")]
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>("Ten", ref fTen, value); }
        }
        TruongHoc fTruongHoc;
        [Association(@"KhoiLopReferencesTruongHoc")]
        [DevExpress.Xpo.DisplayName(@"Trường học")]
        public TruongHoc TruongHoc
        {
            get { return fTruongHoc; }
            set { SetPropertyValue<TruongHoc>("TruongHoc", ref fTruongHoc, value); }
        }
        [Association(@"LopHocReferencesKhoiLop"), Aggregated]
        public XPCollection<LopHoc> LopHocs { get { return GetCollection<LopHoc>("LopHocs"); } }
    }

}
