//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.QuanLyKyThi.DuLieu
{

    public partial class LopHoc : BaseObject
    {
        string fMa;
        [DevExpress.Xpo.DisplayName(@"Mã lớp học")]
        public string Ma
        {
            get { return fMa; }
            set { SetPropertyValue<string>("Ma", ref fMa, value); }
        }
        string fTen;
        [DevExpress.Xpo.DisplayName(@"Lớp học")]
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>("Ten", ref fTen, value); }
        }
        KhoiLop fKhoiLop;
        [Association(@"LopHocReferencesKhoiLop")]
        [DevExpress.Xpo.DisplayName(@"Khối lớp")]
        public KhoiLop KhoiLop
        {
            get { return fKhoiLop; }
            set { SetPropertyValue<KhoiLop>("KhoiLop", ref fKhoiLop, value); }
        }
        [Association(@"HocSinhReferencesLopHoc"), Aggregated]
        public XPCollection<HocSinh> HocSinhs { get { return GetCollection<HocSinh>("HocSinhs"); } }
    }

}
