//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.QuanLyKyThi.DuLieu
{

    public partial class MonThi : BaseObject
    {
        KhoaThi fId_KhoaThi;
        [Association(@"MonThiReferencesKhoaThi")]
        public KhoaThi Id_KhoaThi
        {
            get { return fId_KhoaThi; }
            set { SetPropertyValue<KhoaThi>("Id_KhoaThi", ref fId_KhoaThi, value); }
        }
        MonHoc fId_MonHoc;
        public MonHoc Id_MonHoc
        {
            get { return fId_MonHoc; }
            set { SetPropertyValue<MonHoc>("Id_MonHoc", ref fId_MonHoc, value); }
        }
        int fThoiGian;
        [DevExpress.Xpo.DisplayName(@"Thời gian (phút)")]
        public int ThoiGian
        {
            get { return fThoiGian; }
            set { SetPropertyValue<int>("ThoiGian", ref fThoiGian, value); }
        }
        int fHinhThucThi;
        [DevExpress.Xpo.DisplayName(@"Hình thức thi")]
        public int HinhThucThi
        {
            get { return fHinhThucThi; }
            set { SetPropertyValue<int>("HinhThucThi", ref fHinhThucThi, value); }
        }
    }

}
