//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.QuanLyKyThi.DuLieu
{

    public partial class PhanQuyen : BaseObject
    {
        NhomNguoiDung fNhomNguoiDung;
        [Association(@"PhanQuyenReferencesNhomNguoiDung")]
        [DevExpress.Xpo.DisplayName(@"Nhóm người dùng")]
        public NhomNguoiDung NhomNguoiDung
        {
            get { return fNhomNguoiDung; }
            set { SetPropertyValue<NhomNguoiDung>("NhomNguoiDung", ref fNhomNguoiDung, value); }
        }
        ChucNang fChucNang;
        [Association(@"PhanQuyenReferencesChucNang")]
        [DevExpress.Xpo.DisplayName(@"Chức năng")]
        public ChucNang ChucNang
        {
            get { return fChucNang; }
            set { SetPropertyValue<ChucNang>("ChucNang", ref fChucNang, value); }
        }
        bool fTruyCap;
        [DevExpress.Xpo.DisplayName(@"Truy cập")]
        public bool TruyCap
        {
            get { return fTruyCap; }
            set { SetPropertyValue<bool>("TruyCap", ref fTruyCap, value); }
        }
        bool fThem;
        [DevExpress.Xpo.DisplayName(@"Thêm")]
        public bool Them
        {
            get { return fThem; }
            set { SetPropertyValue<bool>("Them", ref fThem, value); }
        }
        bool fSua;
        [DevExpress.Xpo.DisplayName(@"Sửa")]
        public bool Sua
        {
            get { return fSua; }
            set { SetPropertyValue<bool>("Sua", ref fSua, value); }
        }
        bool fXoa;
        [DevExpress.Xpo.DisplayName(@"Xóa")]
        public bool Xoa
        {
            get { return fXoa; }
            set { SetPropertyValue<bool>("Xoa", ref fXoa, value); }
        }
    }

}
