//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.QuanLyKyThi.DuLieu
{

    public partial class ThiSinh : BaseObject
    {
        KhoaThi fId_KhoaThi;
        [Association(@"ThiSinhReferencesKhoaThi")]
        public KhoaThi Id_KhoaThi
        {
            get { return fId_KhoaThi; }
            set { SetPropertyValue<KhoaThi>("Id_KhoaThi", ref fId_KhoaThi, value); }
        }
        HocSinh fId_HocSinh;
        public HocSinh Id_HocSinh
        {
            get { return fId_HocSinh; }
            set { SetPropertyValue<HocSinh>("Id_HocSinh", ref fId_HocSinh, value); }
        }
    }

}
