//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.QuanLyKyThi.DuLieu
{

    public partial class TruongHoc : BaseObject
    {
        string fMa;
        [DevExpress.Xpo.DisplayName(@"Mã trường học")]
        public string Ma
        {
            get { return fMa; }
            set { SetPropertyValue<string>("Ma", ref fMa, value); }
        }
        string fTen;
        [DevExpress.Xpo.DisplayName(@"Trường học")]
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>("Ten", ref fTen, value); }
        }
        [Association(@"KhoiLopReferencesTruongHoc"), Aggregated]
        public XPCollection<KhoiLop> KhoiLops { get { return GetCollection<KhoiLop>("KhoiLops"); } }
    }

}
