//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyDoanVien.DuLieu
{

    [NonPersistent]
    public partial class BaseObject : XPBaseObject
    {
        int fId;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        DateTime fUpdateAt;
        [DevExpress.Xpo.DisplayName(@"Cập nhật lúc")]
        public DateTime UpdateAt
        {
            get { return fUpdateAt; }
            set { SetPropertyValue<DateTime>("UpdateAt", ref fUpdateAt, value); }
        }
        string fUpdateBy;
        [DevExpress.Xpo.DisplayName(@"Cập nhật bởi")]
        public string UpdateBy
        {
            get { return fUpdateBy; }
            set { SetPropertyValue<string>("UpdateBy", ref fUpdateBy, value); }
        }
    }

}
