//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyDoanVien.DuLieu
{

    public partial class ChucNang : BaseObject
    {
        string fMa;
        [DevExpress.Xpo.DisplayName(@"Mã")]
        public string Ma
        {
            get { return fMa; }
            set { SetPropertyValue<string>("Ma", ref fMa, value); }
        }
        string fTen;
        [DevExpress.Xpo.DisplayName(@"Chức năng")]
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>("Ten", ref fTen, value); }
        }
        ChucNang fCha;
        [Association(@"ChucNangReferencesChucNang")]
        [DevExpress.Xpo.DisplayName(@"Cấp trên")]
        public ChucNang Cha
        {
            get { return fCha; }
            set { SetPropertyValue<ChucNang>("Cha", ref fCha, value); }
        }
        [Association(@"ChucNangReferencesChucNang"), Aggregated]
        public XPCollection<ChucNang> ChucNangCollection { get { return GetCollection<ChucNang>("ChucNangCollection"); } }
        [Association(@"PhanQuyenReferencesChucNang"), Aggregated]
        public XPCollection<PhanQuyen> PhanQuyens { get { return GetCollection<PhanQuyen>("PhanQuyens"); } }
    }

}
