//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyDoanVien.DuLieu
{

    public partial class DonVi : BaseObject
    {
        string fTen;
        [DevExpress.Xpo.DisplayName(@"Đơn vị")]
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>("Ten", ref fTen, value); }
        }
        string fMa;
        [DevExpress.Xpo.DisplayName(@"Mã")]
        public string Ma
        {
            get { return fMa; }
            set { SetPropertyValue<string>("Ma", ref fMa, value); }
        }
        int fCap;
        [DevExpress.Xpo.DisplayName(@"Cấp")]
        public int Cap
        {
            get { return fCap; }
            set { SetPropertyValue<int>("Cap", ref fCap, value); }
        }
        DonVi fCha;
        [Association(@"DonViReferencesDonVi")]
        [DevExpress.Xpo.DisplayName(@"Cấp trên")]
        public DonVi Cha
        {
            get { return fCha; }
            set { SetPropertyValue<DonVi>("Cha", ref fCha, value); }
        }
        [Association(@"DonViReferencesDonVi"), Aggregated]
        public XPCollection<DonVi> DonViCollection { get { return GetCollection<DonVi>("DonViCollection"); } }
    }

}
