//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyDoanVien.DuLieu
{

    public partial class KyLuat : BaseObject
    {
        NhanSu fNhanSu;
        [DevExpress.Xpo.DisplayName(@"Nhân sự")]
        public NhanSu NhanSu
        {
            get { return fNhanSu; }
            set { SetPropertyValue<NhanSu>("NhanSu", ref fNhanSu, value); }
        }
        HinhThucKyLuat fHinhThucKyLuat;
        [DevExpress.Xpo.DisplayName(@"Hình thức KL")]
        public HinhThucKyLuat HinhThucKyLuat
        {
            get { return fHinhThucKyLuat; }
            set { SetPropertyValue<HinhThucKyLuat>("HinhThucKyLuat", ref fHinhThucKyLuat, value); }
        }
        string fNoiDungKyLuat;
        [DevExpress.Xpo.DisplayName(@"Nội dung KL")]
        public string NoiDungKyLuat
        {
            get { return fNoiDungKyLuat; }
            set { SetPropertyValue<string>("NoiDungKyLuat", ref fNoiDungKyLuat, value); }
        }
        DateTime fNgayKyLuat;
        [DevExpress.Xpo.DisplayName(@"Ngày KL")]
        public DateTime NgayKyLuat
        {
            get { return fNgayKyLuat; }
            set { SetPropertyValue<DateTime>("NgayKyLuat", ref fNgayKyLuat, value); }
        }
    }

}
