//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyDoanVien.DuLieu
{

    public partial class NguoiDung : BaseObject
    {
        string fHoVaTen;
        [DevExpress.Xpo.DisplayName(@"Họ và tên")]
        public string HoVaTen
        {
            get { return fHoVaTen; }
            set { SetPropertyValue<string>("HoVaTen", ref fHoVaTen, value); }
        }
        string fTaiKhoan;
        [DevExpress.Xpo.DisplayName(@"Tài khoản")]
        public string TaiKhoan
        {
            get { return fTaiKhoan; }
            set { SetPropertyValue<string>("TaiKhoan", ref fTaiKhoan, value); }
        }
        string fMatKhau;
        [DevExpress.Xpo.DisplayName(@"Mật khẩu")]
        public string MatKhau
        {
            get { return fMatKhau; }
            set { SetPropertyValue<string>("MatKhau", ref fMatKhau, value); }
        }
        string fDienThoai;
        [DevExpress.Xpo.DisplayName(@"Điện thoại")]
        public string DienThoai
        {
            get { return fDienThoai; }
            set { SetPropertyValue<string>("DienThoai", ref fDienThoai, value); }
        }
        string fEmailLienHe;
        [DevExpress.Xpo.DisplayName(@"Email liên hệ")]
        public string EmailLienHe
        {
            get { return fEmailLienHe; }
            set { SetPropertyValue<string>("EmailLienHe", ref fEmailLienHe, value); }
        }
        bool fHoatDong;
        [DevExpress.Xpo.DisplayName(@"Hoạt động")]
        public bool HoatDong
        {
            get { return fHoatDong; }
            set { SetPropertyValue<bool>("HoatDong", ref fHoatDong, value); }
        }
        NhomNguoiDung fNhom;
        [Association(@"NguoiDungReferencesNhomNguoiDung")]
        [DevExpress.Xpo.DisplayName(@"Nhóm")]
        public NhomNguoiDung Nhom
        {
            get { return fNhom; }
            set { SetPropertyValue<NhomNguoiDung>("Nhom", ref fNhom, value); }
        }
        bool fQuanTri;
        [DevExpress.Xpo.DisplayName(@"Quản trị")]
        public bool QuanTri
        {
            get { return fQuanTri; }
            set { SetPropertyValue<bool>("QuanTri", ref fQuanTri, value); }
        }
    }

}
