//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyDoanVien.DuLieu
{

    public partial class NienKhoa : BaseObject
    {
        string fTen;
        [DevExpress.Xpo.DisplayName(@"Niên khóa")]
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>("Ten", ref fTen, value); }
        }
        bool fSuDung;
        [DevExpress.Xpo.DisplayName(@"Sử dụng")]
        public bool SuDung
        {
            get { return fSuDung; }
            set { SetPropertyValue<bool>("SuDung", ref fSuDung, value); }
        }
    }

}
