//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyDoanVien.DuLieu
{

    public partial class QuaTrinhCongTac : BaseObject
    {
        NhanSu fNhanSu;
        [Association(@"QuaTrinhCongTacReferencesNhanSu")]
        public NhanSu NhanSu
        {
            get { return fNhanSu; }
            set { SetPropertyValue<NhanSu>("NhanSu", ref fNhanSu, value); }
        }
        string fTuThangNam;
        [DevExpress.Xpo.DisplayName(@"Từ tháng, năm")]
        public string TuThangNam
        {
            get { return fTuThangNam; }
            set { SetPropertyValue<string>("TuThangNam", ref fTuThangNam, value); }
        }
        string fDenThangNam;
        [DevExpress.Xpo.DisplayName(@"Đến tháng, năm")]
        public string DenThangNam
        {
            get { return fDenThangNam; }
            set { SetPropertyValue<string>("DenThangNam", ref fDenThangNam, value); }
        }
        string fChucDanh_ChucVu_DonViCongTac;
        [DevExpress.Xpo.DisplayName(@"Chức danh, chức vụ, đơn vị công tác")]
        public string ChucDanh_ChucVu_DonViCongTac
        {
            get { return fChucDanh_ChucVu_DonViCongTac; }
            set { SetPropertyValue<string>("ChucDanh_ChucVu_DonViCongTac", ref fChucDanh_ChucVu_DonViCongTac, value); }
        }
    }

}
