//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyDoanVien.DuLieu
{

    public partial class VanBan : BaseObject
    {
        int fKieu;
        [DevExpress.Xpo.DisplayName(@"Kiểu")]
        public int Kieu
        {
            get { return fKieu; }
            set { SetPropertyValue<int>("Kieu", ref fKieu, value); }
        }
        string fSoKyHieu;
        [DevExpress.Xpo.DisplayName(@"Số ký hiệu")]
        public string SoKyHieu
        {
            get { return fSoKyHieu; }
            set { SetPropertyValue<string>("SoKyHieu", ref fSoKyHieu, value); }
        }
        LoaiVanBan fLoaiVanBan;
        [Association(@"VanBanReferencesLoaiVanBan")]
        [DevExpress.Xpo.DisplayName(@"Loại văn bản")]
        public LoaiVanBan LoaiVanBan
        {
            get { return fLoaiVanBan; }
            set { SetPropertyValue<LoaiVanBan>("LoaiVanBan", ref fLoaiVanBan, value); }
        }
        DateTime fNgayBanHanh;
        [DevExpress.Xpo.DisplayName(@"Ngày ban hành")]
        public DateTime NgayBanHanh
        {
            get { return fNgayBanHanh; }
            set { SetPropertyValue<DateTime>("NgayBanHanh", ref fNgayBanHanh, value); }
        }
        DateTime fNgayHieuLuc;
        [DevExpress.Xpo.DisplayName(@"Ngày hiệu lực")]
        public DateTime NgayHieuLuc
        {
            get { return fNgayHieuLuc; }
            set { SetPropertyValue<DateTime>("NgayHieuLuc", ref fNgayHieuLuc, value); }
        }
        string fCoQuanBanHanh;
        [DevExpress.Xpo.DisplayName(@"Cơ quan ban hành")]
        public string CoQuanBanHanh
        {
            get { return fCoQuanBanHanh; }
            set { SetPropertyValue<string>("CoQuanBanHanh", ref fCoQuanBanHanh, value); }
        }
        string fNguoiKy;
        [DevExpress.Xpo.DisplayName(@"Người ký")]
        public string NguoiKy
        {
            get { return fNguoiKy; }
            set { SetPropertyValue<string>("NguoiKy", ref fNguoiKy, value); }
        }
        string fNoiNhan;
        [DevExpress.Xpo.DisplayName(@"Nơi nhận")]
        public string NoiNhan
        {
            get { return fNoiNhan; }
            set { SetPropertyValue<string>("NoiNhan", ref fNoiNhan, value); }
        }
        string fTrichYeu;
        [DevExpress.Xpo.DisplayName(@"Trích yếu")]
        public string TrichYeu
        {
            get { return fTrichYeu; }
            set { SetPropertyValue<string>("TrichYeu", ref fTrichYeu, value); }
        }
        [Association(@"TepVanBanReferencesVanBan"), Aggregated]
        public XPCollection<TepVanBan> TepVanBans { get { return GetCollection<TepVanBan>("TepVanBans"); } }
    }

}
